//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace VizeDosyaükleme.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Dosya
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Dosya()
        {
            this.Konu = new HashSet<Konu>();
        }
    
        public int dosyaId { get; set; }
        public string dosyaAdi { get; set; }
        public string dosyaYolu { get; set; }
        public int konuByID { get; set; }
        public int dosyaKodu { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Konu> Konu { get; set; }
    }
}
