//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace VizeDosyaükleme.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Konu
    {
        public int konuId { get; set; }
        public string konuAdi { get; set; }
        public int dersById { get; set; }
        public int dosyaById { get; set; }
        public int konuKodu { get; set; }
    
        public virtual Ders Ders { get; set; }
        public virtual Dosya Dosya { get; set; }
    }
}
